"""add_designation_degree_experience

Revision ID: 063fc58f5405
Revises: b7e3f8a91c2d
Create Date: 2026-09-19 00:07:30.218934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "063fc58f5405"
down_revision: Union[str, None] = "b7e3f8a91c2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "controller_invites" not in tables:
        op.create_table(
            "controller_invites",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("code_hash", sa.String(length=64), nullable=False),
            sa.Column("role", sa.String(length=50), nullable=False),
            sa.Column("department", sa.String(length=100), nullable=False),
            sa.Column("created_by", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("expires_at", sa.DateTime(), nullable=False),
            sa.Column("max_uses", sa.Integer(), nullable=False),
            sa.Column("used_count", sa.Integer(), nullable=False),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("used_by", sa.Integer(), nullable=True),
            sa.Column("used_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["created_by"],
                ["users.id"],
            ),
            sa.ForeignKeyConstraint(
                ["used_by"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_controller_invites_code_hash"),
            "controller_invites",
            ["code_hash"],
            unique=True,
        )
        op.create_index(
            op.f("ix_controller_invites_id"), "controller_invites", ["id"], unique=False
        )

    profile_cols = [c["name"] for c in inspector.get_columns("profiles")]
    if "designation" not in profile_cols:
        op.add_column(
            "profiles", sa.Column("designation", sa.String(length=100), nullable=True)
        )
    if "degree" not in profile_cols:
        op.add_column(
            "profiles", sa.Column("degree", sa.String(length=100), nullable=True)
        )
    if "experience" not in profile_cols:
        op.add_column(
            "profiles", sa.Column("experience", sa.String(length=100), nullable=True)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "experience")
    op.drop_column("profiles", "degree")
    op.drop_column("profiles", "designation")
    op.drop_index(op.f("ix_controller_invites_id"), table_name="controller_invites")
    op.drop_index(
        op.f("ix_controller_invites_code_hash"), table_name="controller_invites"
    )
    op.drop_table("controller_invites")
    # ### end Alembic commands ###
