"""add_conversation_id_to_clubs

Revision ID: 1d9b6b6aae91
Revises: 063fc58f5405
Create Date: 2026-09-19 00:14:34.160497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1d9b6b6aae91"
down_revision: Union[str, None] = "063fc58f5405"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("clubs")]
    if "conversation_id" not in columns:
        op.add_column(
            "clubs", sa.Column("conversation_id", sa.Integer(), nullable=True)
        )
        op.create_foreign_key(
            "fk_clubs_conversation_id",
            "clubs",
            "conversations",
            ["conversation_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "clubs", type_="foreignkey")
    op.drop_column("clubs", "conversation_id")
    # ### end Alembic commands ###
