"""add_missing_profile_columns

Revision ID: 7072a3e47bba
Revises: 9d4e5f6a7b8c
Create Date: 2026-10-01 10:13:47.786759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7072a3e47bba"
down_revision: Union[str, None] = "9d4e5f6a7b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notify_on_like", sa.Boolean(), nullable=False),
        sa.Column("notify_on_comment", sa.Boolean(), nullable=False),
        sa.Column("notify_on_connection_request", sa.Boolean(), nullable=False),
        sa.Column("notify_on_event_rsvp", sa.Boolean(), nullable=False),
        sa.Column("notify_on_message", sa.Boolean(), nullable=False),
        sa.Column("notify_on_job_alert", sa.Boolean(), nullable=False),
        sa.Column("notify_on_general", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_notification_prefs_user"),
    )
    op.create_index(
        op.f("ix_notification_preferences_id"),
        "notification_preferences",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_club_gallery_items_id"), "club_gallery_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_club_resources_id"), "club_resources", ["id"], unique=False
    )
    op.add_column("clubs", sa.Column("head_id", sa.Integer(), nullable=True))
    op.add_column("clubs", sa.Column("co_head_id", sa.Integer(), nullable=True))
    op.add_column(
        "clubs", sa.Column("faculty_coordinator_id", sa.Integer(), nullable=True)
    )
    op.create_index(op.f("ix_clubs_co_head_id"), "clubs", ["co_head_id"], unique=False)
    op.create_index(
        op.f("ix_clubs_faculty_coordinator_id"),
        "clubs",
        ["faculty_coordinator_id"],
        unique=False,
    )
    op.create_index(op.f("ix_clubs_head_id"), "clubs", ["head_id"], unique=False)
    op.create_foreign_key(
        "fk_clubs_co_head_id_users", "clubs", "users", ["co_head_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_clubs_head_id_users", "clubs", "users", ["head_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_clubs_faculty_coordinator_id_users",
        "clubs",
        "users",
        ["faculty_coordinator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_conv_participants_user_conv",
        "conversation_participants",
        ["user_id", "conversation_id"],
        unique=False,
    )
    # events already has a foreign key to users, ensure it's named
    # op.drop_constraint(op.f('events_faculty_coordinator_id_fkey'), 'events', type_='foreignkey')
    # op.create_foreign_key('fk_events_faculty_coordinator_id_users', 'events', 'users', ['faculty_coordinator_id'], ['id'])
    op.alter_column(
        "faculty_opportunities",
        "opportunity_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "JOB",
            "INTERNSHIP",
            "RESEARCH",
            "MENTORSHIP",
            name="opportunity_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'JOB'::character varying"),
    )
    op.alter_column(
        "faculty_opportunities",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "OPEN", "CLOSED", name="opportunity_status_enum", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'OPEN'::character varying"),
    )
    op.create_index(
        op.f("ix_faculty_opportunities_id"),
        "faculty_opportunities",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_likes_post_user"), table_name="likes")
    op.drop_index(op.f("ix_messages_conversation_time"), table_name="messages")
    op.create_index(
        "ix_messages_conv_unread",
        "messages",
        ["conversation_id", "is_read"],
        unique=False,
    )
    op.create_index(
        "ix_messages_sender_receiver",
        "messages",
        ["sender_id", "receiver_id"],
        unique=False,
    )
    op.alter_column(
        "notifications", "is_read", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index(
        op.f("ix_notifications_user_unread"),
        table_name="notifications",
        postgresql_where="(is_read = false)",
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_notifications_user_id_is_read",
        "notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.alter_column(
        "opportunity_applications",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "APPLIED",
            "PENDING",
            "SHORTLISTED",
            "ACCEPTED",
            "REJECTED",
            name="opportunity_application_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.create_index(
        op.f("ix_opportunity_applications_id"),
        "opportunity_applications",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.create_index(op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False)
    op.add_column(
        "profiles", sa.Column("placement_status", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "placement_status")
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.create_index(
        op.f("ix_posts_created_at"),
        "posts",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        op.f("ix_opportunity_applications_id"), table_name="opportunity_applications"
    )
    op.alter_column(
        "opportunity_applications",
        "status",
        existing_type=sa.Enum(
            "APPLIED",
            "PENDING",
            "SHORTLISTED",
            "ACCEPTED",
            "REJECTED",
            name="opportunity_application_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.drop_index("ix_notifications_user_id_is_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_user_unread"),
        "notifications",
        ["user_id", "is_read"],
        unique=False,
        postgresql_where="(is_read = false)",
    )
    op.alter_column(
        "notifications", "is_read", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index("ix_messages_sender_receiver", table_name="messages")
    op.drop_index("ix_messages_conv_unread", table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_time"),
        "messages",
        ["conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_likes_post_user"), "likes", ["post_id", "user_id"], unique=False
    )
    op.drop_index(
        op.f("ix_faculty_opportunities_id"), table_name="faculty_opportunities"
    )
    op.alter_column(
        "faculty_opportunities",
        "status",
        existing_type=sa.Enum(
            "OPEN", "CLOSED", name="opportunity_status_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'OPEN'::character varying"),
    )
    op.alter_column(
        "faculty_opportunities",
        "opportunity_type",
        existing_type=sa.Enum(
            "JOB",
            "INTERNSHIP",
            "RESEARCH",
            "MENTORSHIP",
            name="opportunity_type_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'JOB'::character varying"),
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key(
        op.f("events_faculty_coordinator_id_fkey"),
        "events",
        "users",
        ["faculty_coordinator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        "ix_conv_participants_user_conv", table_name="conversation_participants"
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "clubs", type_="foreignkey")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "clubs", type_="foreignkey")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "clubs", type_="foreignkey")
    op.drop_index(op.f("ix_clubs_head_id"), table_name="clubs")
    op.drop_index(op.f("ix_clubs_faculty_coordinator_id"), table_name="clubs")
    op.drop_index(op.f("ix_clubs_co_head_id"), table_name="clubs")
    op.drop_column("clubs", "faculty_coordinator_id")
    op.drop_column("clubs", "co_head_id")
    op.drop_column("clubs", "head_id")
    op.drop_index(op.f("ix_club_resources_id"), table_name="club_resources")
    op.drop_index(op.f("ix_club_gallery_items_id"), table_name="club_gallery_items")
    op.drop_index(
        op.f("ix_notification_preferences_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
