"""add_analytics_and_endorsements

Revision ID: 7b2cba85bb69
Revises: 7d65692d5a3f
Create Date: 2026-07-26 13:54:03.905348

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b2cba85bb69"
down_revision: str | None = "7d65692d5a3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_engagements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("engagement_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_engagements_id"), "post_engagements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_post_engagements_post_id"),
        "post_engagements",
        ["post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_post_engagements_user_id"),
        "post_engagements",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "profile_views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("viewer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["viewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_views_id"), "profile_views", ["id"], unique=False)
    op.create_index(
        op.f("ix_profile_views_profile_id"),
        "profile_views",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_views_viewer_id"), "profile_views", ["viewer_id"], unique=False
    )
    op.create_table(
        "skill_endorsements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("skill_name", sa.String(length=100), nullable=False),
        sa.Column("endorser_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["endorser_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "skill_name", "endorser_id", name="uq_profile_skill_endorser"
        ),
    )
    op.create_index(
        op.f("ix_skill_endorsements_endorser_id"),
        "skill_endorsements",
        ["endorser_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_endorsements_id"), "skill_endorsements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_skill_endorsements_profile_id"),
        "skill_endorsements",
        ["profile_id"],
        unique=False,
    )
    op.add_column("events", sa.Column("club_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_events_club_id"), "events", ["club_id"], unique=False)
    op.create_foreign_key(None, "events", "clubs", ["club_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_club_id"), table_name="events")
    op.drop_column("events", "club_id")
    op.drop_index(
        op.f("ix_skill_endorsements_profile_id"), table_name="skill_endorsements"
    )
    op.drop_index(op.f("ix_skill_endorsements_id"), table_name="skill_endorsements")
    op.drop_index(
        op.f("ix_skill_endorsements_endorser_id"), table_name="skill_endorsements"
    )
    op.drop_table("skill_endorsements")
    op.drop_index(op.f("ix_profile_views_viewer_id"), table_name="profile_views")
    op.drop_index(op.f("ix_profile_views_profile_id"), table_name="profile_views")
    op.drop_index(op.f("ix_profile_views_id"), table_name="profile_views")
    op.drop_table("profile_views")
    op.drop_index(op.f("ix_post_engagements_user_id"), table_name="post_engagements")
    op.drop_index(op.f("ix_post_engagements_post_id"), table_name="post_engagements")
    op.drop_index(op.f("ix_post_engagements_id"), table_name="post_engagements")
    op.drop_table("post_engagements")
    # ### end Alembic commands ###
