"""Add 10th and 12th percentages

Revision ID: 9a60b941ccfa
Revises: f1a2b3c4d5e6
Create Date: 2026-09-11 00:50:14.964223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a60b941ccfa'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.add_column('education', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('google_form_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('leetcode_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('tenth_percentage', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('twelfth_diploma_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'twelfth_diploma_percentage')
    op.drop_column('profiles', 'tenth_percentage')
    op.drop_column('profiles', 'phone_number')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'leetcode_url')
    op.drop_column('profiles', 'github_url')
    op.drop_column('events', 'google_form_url')
    op.drop_column('education', 'percentage')
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notify_on_like', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_comment', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_connection_request', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_event_rsvp', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_message', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_job_alert', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_general', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_prefs_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
