"""add_posts_events_clubs

Revision ID: adc0ea3bd499
Revises: dd65b3e224b2
Create Date: 2026-07-15 20:05:34.640590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_posts_events_clubs

Revision ID: adc0ea3bd499
Revises: dd65b3e224b2
Create Date: 2026-07-15 20:05:34.640590

"""


# revision identifiers, used by Alembic.
revision: str = "adc0ea3bd499"
down_revision: Union[str, None] = "dd65b3e224b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create PostgreSQL ENUM types if they don't exist
    connectionstatus = postgresql.ENUM(
        "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
    )
    connectionstatus.create(op.get_bind(), checkfirst=True)

    eventstatus = postgresql.ENUM(
        "DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED", name="eventstatus"
    )
    eventstatus.create(op.get_bind(), checkfirst=True)

    postvisibility = postgresql.ENUM(
        "PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"
    )
    postvisibility.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_categories_id"), "event_categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_event_categories_name"), "event_categories", ["name"], unique=True
    )
    op.create_table(
        "rsvps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("GOING", "MAYBE", "NOT_GOING", name="rsvpstatus"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_rsvp_event_user"),
    )
    op.create_index(op.f("ix_rsvps_event_id"), "rsvps", ["event_id"], unique=False)
    op.create_index(op.f("ix_rsvps_id"), "rsvps", ["id"], unique=False)
    op.create_index(op.f("ix_rsvps_user_id"), "rsvps", ["user_id"], unique=False)
    op.add_column("comments", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "comments", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"),
        nullable=False,
        postgresql_using="status::connectionstatus",
    )
    op.add_column(
        "events", sa.Column("banner_image_url", sa.String(length=500), nullable=True)
    )
    op.add_column("events", sa.Column("start_datetime", sa.DateTime(), nullable=False))
    op.add_column("events", sa.Column("end_datetime", sa.DateTime(), nullable=True))
    op.add_column("events", sa.Column("max_capacity", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("is_rsvp_enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "events",
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED", name="eventstatus"),
            nullable=False,
        ),
    )
    op.add_column("events", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "events",
        "location",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    op.alter_column(
        "events", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(
        op.f("ix_events_category_id"), "events", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False
    )
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index(op.f("ix_events_title"), "events", ["title"], unique=False)
    op.create_foreign_key(None, "events", "event_categories", ["category_id"], ["id"])
    op.drop_column("events", "date")
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(op.f("ix_likes_post_id"), "likes", ["post_id"], unique=False)
    op.create_index(op.f("ix_likes_user_id"), "likes", ["user_id"], unique=False)
    op.add_column(
        "posts",
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"),
            nullable=False,
        ),
    )
    op.add_column("posts", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "posts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.alter_column(
        "posts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("posts", "updated_at")
    op.drop_column("posts", "visibility")
    op.drop_index(op.f("ix_likes_user_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_post_id"), table_name="likes")
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.add_column(
        "events",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_title"), table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_index(op.f("ix_events_category_id"), table_name="events")
    op.alter_column(
        "events", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "events",
        "location",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.drop_column("events", "updated_at")
    op.drop_column("events", "category_id")
    op.drop_column("events", "status")
    op.drop_column("events", "is_rsvp_enabled")
    op.drop_column("events", "max_capacity")
    op.drop_column("events", "end_datetime")
    op.drop_column("events", "start_datetime")
    op.drop_column("events", "banner_image_url")
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.Enum(
            "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
        ),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.alter_column(
        "comments", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("comments", "updated_at")
    op.drop_index(op.f("ix_rsvps_user_id"), table_name="rsvps")
    op.drop_index(op.f("ix_rsvps_id"), table_name="rsvps")
    op.drop_index(op.f("ix_rsvps_event_id"), table_name="rsvps")
    op.drop_table("rsvps")
    op.drop_index(op.f("ix_event_categories_name"), table_name="event_categories")
    op.drop_index(op.f("ix_event_categories_id"), table_name="event_categories")
    op.drop_table("event_categories")
    # ### end Alembic commands ###

    # Drop custom PostgreSQL ENUM types
    connectionstatus = postgresql.ENUM(
        "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
    )
    connectionstatus.drop(op.get_bind(), checkfirst=True)

    eventstatus = postgresql.ENUM(
        "DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED", name="eventstatus"
    )
    eventstatus.drop(op.get_bind(), checkfirst=True)

    postvisibility = postgresql.ENUM(
        "PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"
    )
    postvisibility.drop(op.get_bind(), checkfirst=True)
