"""add_education_and_profile_picture

Revision ID: dd65b3e224b2
Revises: c68f48f60cd8
Create Date: 2026-07-14 21:11:14.131587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd65b3e224b2'
down_revision: Union[str, None] = 'c68f48f60cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the connectionstatus enum type in PostgreSQL
    connection_status = sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='connectionstatus')
    connection_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.alter_column('connections', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='connectionstatus'),
               postgresql_using="status::connectionstatus",
               nullable=False)
    op.add_column('profiles', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_picture')
    op.alter_column('connections', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='connectionstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    # ### end Alembic commands ###
