"""add_gpa_projects_certifications

Revision ID: e81b98b21354
Revises: dd65b3e224b2
Create Date: 2026-07-18 19:55:11.914833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e81b98b21354"
down_revision: str | None = "dd65b3e224b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types manually if they don't exist
    connection_status_enum = postgresql.ENUM(
        "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
    )
    connection_status_enum.create(op.get_bind(), checkfirst=True)
    post_visibility_enum = postgresql.ENUM(
        "PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"
    )
    post_visibility_enum.create(op.get_bind(), checkfirst=True)

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # 1. comments table
    columns_comments = [c["name"] for c in inspector.get_columns("comments")]
    if "updated_at" not in columns_comments:
        op.add_column(
            "comments",
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now(),
            ),
        )
    for c in inspector.get_columns("comments"):
        if c["name"] == "created_at" and c["nullable"]:
            op.alter_column(
                "comments",
                "created_at",
                existing_type=postgresql.TIMESTAMP(),
                nullable=False,
            )

    indexes_comments = [idx["name"] for idx in inspector.get_indexes("comments")]
    if "ix_comments_author_id" not in indexes_comments:
        op.create_index(
            op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
        )
    if "ix_comments_post_id" not in indexes_comments:
        op.create_index(
            op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False
        )

    # 2. connections table
    columns_connections = inspector.get_columns("connections")
    status_column = next(
        (c for c in columns_connections if c["name"] == "status"), None
    )
    if status_column and isinstance(status_column["type"], sa.VARCHAR):
        op.alter_column(
            "connections",
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"),
            nullable=False,
            postgresql_using="status::connectionstatus",
        )

    # 3. education table
    columns_education = [c["name"] for c in inspector.get_columns("education")]
    if "gpa" not in columns_education:
        op.add_column("education", sa.Column("gpa", sa.Float(), nullable=True))

    # 4. likes table
    for c in inspector.get_columns("likes"):
        if c["name"] == "created_at" and c["nullable"]:
            op.alter_column(
                "likes",
                "created_at",
                existing_type=postgresql.TIMESTAMP(),
                nullable=False,
            )

    indexes_likes = [idx["name"] for idx in inspector.get_indexes("likes")]
    if "ix_likes_post_id" not in indexes_likes:
        op.create_index(op.f("ix_likes_post_id"), "likes", ["post_id"], unique=False)
    if "ix_likes_user_id" not in indexes_likes:
        op.create_index(op.f("ix_likes_user_id"), "likes", ["user_id"], unique=False)

    # 5. posts table
    columns_posts = [c["name"] for c in inspector.get_columns("posts")]
    if "visibility" not in columns_posts:
        op.add_column(
            "posts",
            sa.Column(
                "visibility",
                sa.Enum("PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"),
                nullable=False,
                server_default="PUBLIC",
            ),
        )
    if "updated_at" not in columns_posts:
        op.add_column(
            "posts",
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now(),
            ),
        )
    for c in inspector.get_columns("posts"):
        if c["name"] == "created_at" and c["nullable"]:
            op.alter_column(
                "posts",
                "created_at",
                existing_type=postgresql.TIMESTAMP(),
                nullable=False,
            )

    indexes_posts = [idx["name"] for idx in inspector.get_indexes("posts")]
    if "ix_posts_author_id" not in indexes_posts:
        op.create_index(
            op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False
        )

    # 6. profiles table
    columns_profiles = [c["name"] for c in inspector.get_columns("profiles")]
    if "certifications" not in columns_profiles:
        op.add_column("profiles", sa.Column("certifications", sa.JSON(), nullable=True))
    if "projects" not in columns_profiles:
        op.add_column("profiles", sa.Column("projects", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "projects")
    op.drop_column("profiles", "certifications")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.alter_column(
        "posts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("posts", "updated_at")
    op.drop_column("posts", "visibility")
    op.drop_index(op.f("ix_likes_user_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_post_id"), table_name="likes")
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("education", "gpa")
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.Enum(
            "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
        ),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.alter_column(
        "comments", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("comments", "updated_at")
    # ### end Alembic commands ###
