"""add_gpa_projects_certifications

Revision ID: e81b98b21354
Revises: dd65b3e224b2
Create Date: 2026-07-18 19:55:11.914833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e81b98b21354"
down_revision: Union[str, None] = "dd65b3e224b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types manually if they don't exist
    connection_status_enum = postgresql.ENUM(
        "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
    )
    connection_status_enum.create(op.get_bind(), checkfirst=True)
    post_visibility_enum = postgresql.ENUM(
        "PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"
    )
    post_visibility_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "comments",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.alter_column(
        "comments", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"),
        nullable=False,
        postgresql_using="status::connectionstatus",
    )
    op.add_column("education", sa.Column("gpa", sa.Float(), nullable=True))
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(op.f("ix_likes_post_id"), "likes", ["post_id"], unique=False)
    op.create_index(op.f("ix_likes_user_id"), "likes", ["user_id"], unique=False)
    op.add_column(
        "posts",
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "CONNECTIONS", "PRIVATE", name="postvisibility"),
            nullable=False,
            server_default="PUBLIC",
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.alter_column(
        "posts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.add_column("profiles", sa.Column("certifications", sa.JSON(), nullable=True))
    op.add_column("profiles", sa.Column("projects", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "projects")
    op.drop_column("profiles", "certifications")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.alter_column(
        "posts", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("posts", "updated_at")
    op.drop_column("posts", "visibility")
    op.drop_index(op.f("ix_likes_user_id"), table_name="likes")
    op.drop_index(op.f("ix_likes_post_id"), table_name="likes")
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("education", "gpa")
    op.alter_column(
        "connections",
        "status",
        existing_type=sa.Enum(
            "PENDING", "ACCEPTED", "REJECTED", name="connectionstatus"
        ),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.alter_column(
        "comments", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("comments", "updated_at")
    # ### end Alembic commands ###
