"""add conversation and read_receipt models

Revision ID: edbdde4f8149
Revises: 9176aa6b8456
Create Date: 2026-07-20 19:40:57.805175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edbdde4f8149"
down_revision: Union[str, None] = "9176aa6b8456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_table(
        "conversation_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("last_read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "user_id", name="uq_conversation_user"),
    )
    op.create_index(
        op.f("ix_conversation_participants_id"),
        "conversation_participants",
        ["id"],
        unique=False,
    )
    op.create_table(
        "read_receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "message_id", "user_id", name="uq_message_user_read_receipt"
        ),
    )
    op.create_index(op.f("ix_read_receipts_id"), "read_receipts", ["id"], unique=False)
    op.create_index(
        op.f("ix_read_receipts_message_id"),
        "read_receipts",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_read_receipts_user_id"), "read_receipts", ["user_id"], unique=False
    )
    op.add_column("messages", sa.Column("conversation_id", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("read_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "messages", "receiver_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("messages", "is_read", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "messages", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_receiver_id"), "messages", ["receiver_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_receiver_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.alter_column(
        "messages", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("messages", "is_read", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "messages", "receiver_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("messages", "read_at")
    op.drop_column("messages", "conversation_id")
    op.drop_index(op.f("ix_read_receipts_user_id"), table_name="read_receipts")
    op.drop_index(op.f("ix_read_receipts_message_id"), table_name="read_receipts")
    op.drop_index(op.f("ix_read_receipts_id"), table_name="read_receipts")
    op.drop_table("read_receipts")
    op.drop_index(
        op.f("ix_conversation_participants_id"), table_name="conversation_participants"
    )
    op.drop_table("conversation_participants")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
